services:
  - type: web
    name: comparador-panales-chile
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.12"
      - key: RESEND_API_KEY
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: BASE_URL
        value: "https://babyahorro.cl"
